#ifndef RTOS_PORT_PORT_CONFIG_H_
#define RTOS_PORT_PORT_CONFIG_H_

#define PORT_CONFIG_KERNEL_PRIORITY       		5
#define PORT_CONFIG_NVIC_PRIO_BITS				4
#define PORT_CONFIG_BASEPRI_LOCK_VALUE     		(PORT_CONFIG_KERNEL_PRIORITY << (8 - PORT_CONFIG_NVIC_PRIO_BITS))

#define PORT_CONFIG_FLASH_BASE					(0x08000000UL)
#define PORT_CONFIG_FLASH_SIZE_KB				(512UL)
#define PORT_CONFIG_FLASH_SIZE_MPU				(18UL)

#define PORT_CONFIG_SRAM_BASE					(0x20000000UL)
#define PORT_CONFIG_SRAM_SIZE_KB				(128UL)
#define PORT_CONFIG_SRAM_SIZE_MPU				(16UL)

#define PORT_CONFIG_PERIPH_BASE					(0x40000000UL)
#define PORT_CONFIG_PERIPH_SIZE_MB				(512UL)
#define PORT_CONFIG_PERIPH_SIZE_MPU				(28UL)

#ifndef __ASSEMBLER__
	#include <assert.h>

	static_assert(PORT_CONFIG_NVIC_PRIO_BITS == 4, "Error: CONFIG_NVIC_PRIO_BITS must be equal 4 for STM32F411");
#endif


#endif
