/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

#include "RTOS/os_manager.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

OS_CREATE_STACK(stack1_handle, 128);
OS_CREATE_STACK(stack2_handle, 128);

void Task2(void) {
	return;
	/*while(1) {
		GPIOC->ODR |= (GPIO_ODR_OD13);
		for (uint32_t i = 0; i < 100000; i++);
	}*/
}

void Task3(void) {
	while(1) {
		GPIOC->ODR |= (GPIO_ODR_OD13);
		for (uint32_t i = 0; i < 100000; i++);
	}
}

void Task1(void) {
	OS_CreateTaskStatic(Task3, stack2_handle, 1);
	while(1) {
		GPIOC->ODR &= ~(GPIO_ODR_OD13);
		for (uint32_t i = 0; i < 100000; i++);
	}
}

void GPIO_Config(void) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

	GPIOC->MODER &= ~(GPIO_MODER_MODE13);
	GPIOC->MODER |= (0b01 << GPIO_MODER_MODE13_Pos);

	GPIOC->OTYPER &= ~(GPIO_OTYPER_OT13);

	GPIOC->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEED13);

	GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPD13);
	GPIOC->ODR |= (GPIO_ODR_OD13);
}

int main(void)
{
	OS_Initialization();

	OS_TaskHandle_t h1 = OS_CreateTaskStatic(Task1, stack1_handle, 1);
	OS_TaskHandle_t h2 = OS_CreateTaskStatic(Task2, stack2_handle, 1);

	OS_DeleteTask(h1);
	OS_DeleteTask(h2);

	h1 = OS_CreateTaskStatic(Task1, stack1_handle, 1);
	h2 = OS_CreateTaskStatic(Task2, stack2_handle, 1);

	GPIO_Config();

	OS_Start();
}

//Переделать критическую секцию
//Реализовать static assert для проверки стека и т.д.
//Добавить поддержку MPU
//Добавить поддержку FPU
//Добавить unpriveleged mod
//Перенести библиотеки на GitHub

//Вытеснение задач
//Модификация полей контекста ОС обязана быть атомарной
//Частота МК
//ЗНАЧЕНИЕ LR И КОЛИЧЕСТВО РЕГИСТРОВ ЗАВИСЯТ ОТ FPU!
